/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.Dimension;

/**
 *
 * @author annys
 */
public class TestSel extends javax.swing.JFrame {

    String userName;
    public TestSel(String userName) {
        initComponents();
        this.setSize(new Dimension(600,750));
        this.userName = userName;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        anxietyButton = new javax.swing.JButton();
        depressionButton = new javax.swing.JButton();
        eatingButton = new javax.swing.JButton();
        obsessiveButton = new javax.swing.JButton();
        generalButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Take a specific test to compute compatibility with a disorder:");

        anxietyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        anxietyButton.setText("Anxiety disorder questionnaire");
        anxietyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anxietyButtonActionPerformed(evt);
            }
        });

        depressionButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        depressionButton.setText("Depression disorder questionnaire");
        depressionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depressionButtonActionPerformed(evt);
            }
        });

        eatingButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eatingButton.setText("Eating disorder questionnaire");
        eatingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eatingButtonActionPerformed(evt);
            }
        });

        obsessiveButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        obsessiveButton.setText("Obsessive Compulsive Disorder questionnaire");
        obsessiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obsessiveButtonActionPerformed(evt);
            }
        });

        generalButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generalButton.setText("General questionnaire");
        generalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Take a general test to compute compatibility with different disorders:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(obsessiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anxietyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(depressionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eatingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(generalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(anxietyButton)
                .addGap(44, 44, 44)
                .addComponent(depressionButton)
                .addGap(49, 49, 49)
                .addComponent(eatingButton)
                .addGap(49, 49, 49)
                .addComponent(obsessiveButton)
                .addGap(108, 108, 108)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(generalButton)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anxietyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anxietyButtonActionPerformed
        TestAnxiety anxietyFrame = new TestAnxiety(userName, false);
        anxietyFrame.setLocationRelativeTo(null);
        anxietyFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_anxietyButtonActionPerformed

    private void depressionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depressionButtonActionPerformed
        TestDepression depressionFrame = new TestDepression(userName, false);
        depressionFrame.setLocationRelativeTo(null);
        depressionFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_depressionButtonActionPerformed

    private void eatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eatingButtonActionPerformed
        TestEatingDis1 eatingFrame = new TestEatingDis1(userName, false);
        eatingFrame.setLocationRelativeTo(null);
        eatingFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_eatingButtonActionPerformed

    private void obsessiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obsessiveButtonActionPerformed
        TestOCD1 ocdFrame = new TestOCD1(userName, false);
        ocdFrame.setLocationRelativeTo(null);
        ocdFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_obsessiveButtonActionPerformed

    private void generalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalButtonActionPerformed
        TestAnxiety anxietyFrame = new TestAnxiety(userName, true);
        anxietyFrame.setLocationRelativeTo(null);
        anxietyFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_generalButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anxietyButton;
    private javax.swing.JButton depressionButton;
    private javax.swing.JButton eatingButton;
    private javax.swing.JButton generalButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton obsessiveButton;
    // End of variables declaration//GEN-END:variables
}
