/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Pojos.User;
import static Interface.Cover.*;
import static Pojos.Validator.*;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author annys
 */
public class UserInfo extends javax.swing.JFrame {

    /**
     * Creates new form UserInfo
     */
    public UserInfo() {
        initComponents();
        this.setSize(new Dimension(600,750));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        signupButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        FirstPasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        SecondPasswordField = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 750));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Please enter the following information to create a new user:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name and Surname");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Username");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Password");

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });

        signupButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        signupButton.setText("Sign Up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        FirstPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstPasswordFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Confirm Password");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel7.setText("CREATE A NEW USER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTextField)
                                    .addComponent(SecondPasswordField)
                                    .addComponent(FirstPasswordField)
                                    .addComponent(usernameTextField)
                                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(signupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel7)
                .addGap(63, 63, 63)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SecondPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signupButton)
                    .addComponent(backButton))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        String name = nameTextField.getText();
        String ageSt = ageTextField.getText();
        String userName = usernameTextField.getText();
        String password = String.valueOf(FirstPasswordField.getPassword());
        String repassword = String.valueOf(SecondPasswordField.getPassword());
        
        boolean allValueEntered = false;
        boolean valStringb = valString(name);
        boolean valAgeLimitsb = valAgeLimits(5,99,ageSt);
        boolean checkUserNameb = checkUserName(userName);
        boolean checkSamePassword = checkSamePasswrod(password, repassword);
        System.out.println(password);
        System.out.println(repassword);
        if((!nameTextField.getText().isEmpty())&&(!ageTextField.getText().isEmpty())&&(!usernameTextField.getText().isEmpty())&&!(FirstPasswordField.getPassword().length == 0)&&!(SecondPasswordField.getPassword().length == 0)){
            allValueEntered = true;
        }
        if(allValueEntered){
        if((valStringb)&&(valAgeLimitsb)&&(!checkUserNameb)&&(checkSamePassword)){
            int age = Integer.parseInt(ageTextField.getText());
            String encodedPassword = encodePassword(String.valueOf(FirstPasswordField.getPassword()));
            User user = new User(nameTextField.getText(), encodedPassword, usernameTextField.getText(), age);
            saveUserInfo("UserPasswords.txt","data",user);
            this.setVisible(false);
            TestSel testSelectionFrame = new TestSel(user.getUserName());
            testSelectionFrame.setLocationRelativeTo(null); 
            testSelectionFrame.setVisible(true); 
            this.dispose();
            }
        panel2Icons(valStringb,valAgeLimitsb,checkUserNameb,checkSamePassword);
        }
        else{    
        JOptionPane.showMessageDialog(new JFrame(), "Some values are missing!", "Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_signupButtonActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void FirstPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstPasswordFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        Cover cover = new Cover();
        
        cover.setLocationRelativeTo(null); 
        cover.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    public void panel2Icons(boolean valStringb, boolean valAgeLimitsb, boolean checkUserNameb, boolean checkSamePassword)
    {
           if(!valStringb)
           {
               nameTextField.setBorder(new LineBorder(Color.red,2));
               JOptionPane.showMessageDialog(new JFrame(), "Check your values, something is incorrect!", "Error",JOptionPane.ERROR_MESSAGE);
           }else
           {
               nameTextField.setBorder(new LineBorder(Color.black,1));
           }
           if(!valAgeLimitsb)
           {
               ageTextField.setBorder(new LineBorder(Color.red,2));
               JOptionPane.showMessageDialog(new JFrame(), "Age does not fit into real parameters. Check your values!", "Error",JOptionPane.ERROR_MESSAGE);
           }else
           {
               ageTextField.setBorder(new LineBorder(Color.black,1));
           }
           if(checkUserNameb)
           {
               usernameTextField.setBorder(new LineBorder(Color.red,2));
               JOptionPane.showMessageDialog(new JFrame(), "This username already exists!", "Error",JOptionPane.ERROR_MESSAGE);
           }else
           {
               usernameTextField.setBorder(new LineBorder(Color.black,1));
           }
           if(!checkSamePassword)
           {
               FirstPasswordField.setBorder(new LineBorder(Color.red,2));
               SecondPasswordField.setBorder(new LineBorder(Color.red,2));
               JOptionPane.showMessageDialog(new JFrame(), "Please, password must be the same!", "Error",JOptionPane.ERROR_MESSAGE);
           }else
           {
               FirstPasswordField.setBorder(new LineBorder(Color.black,1));
               SecondPasswordField.setBorder(new LineBorder(Color.black,1));
           }
    }
    
    public static boolean checkUserName(String us)
    {
        boolean ans = false;
        User user = null;
        
        ArrayList<User> namePasswords = loadAllUsers("UserPasswords.txt","data");
       
        Iterator it = namePasswords.iterator();
        for(int i = 0; i<namePasswords.size();i++)
        {
            user = (User)it.next();
            if(user.getUserName().equals(us))
            {
                ans = true;
                break;
            }
        }
        
        return ans;
    }
    
    public static boolean checkSamePasswrod(String p1, String p2)
    {   
        System.out.println(p1.equals(p2));
        return p1.equals(p2);
    }
         
    public static void saveUserInfo(String nombreArchivo,String directorio, User user)
    {
        
        FileOutputStream fileOutputStream=null;
        ObjectOutputStream objectOutputStream=null;
        
        ArrayList<User> users = loadAllUsers(nombreArchivo,directorio);
        
        
        
        File fichero = new File(directorio,nombreArchivo);
        
            try{
            
                fileOutputStream = new FileOutputStream(fichero);
                objectOutputStream = new ObjectOutputStream(fileOutputStream);
                users.add(user);
                Iterator<User> it = users.iterator();
                objectOutputStream.writeObject(users.size());
                while(it.hasNext())
                {
                    User us = (User)it.next();

                    objectOutputStream.writeObject(us);
                }
    
            }catch(IOException ex)
            {
            } finally {
                    try {
                        if (fileOutputStream != null) {
                            fileOutputStream.close();
                        }
                    } catch (IOException ex) {
                        ex.printStackTrace();
                        }
                    try {
                        if (objectOutputStream != null) {
                            objectOutputStream.close();
                        }
                   } catch (IOException ex) {
                       ex.printStackTrace();
                }
            }
        
    }
    /*
        private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("Icons/logo_mni.jpg")));
        this.setTitle("LRG");
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField FirstPasswordField;
    private javax.swing.JPasswordField SecondPasswordField;
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
