/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Pojos.Test;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Dimension;

/**
 *
 * @author annys
 */
public class TestEatingDis1 extends javax.swing.JFrame {

    String userName;
    boolean generalTest = false;
    int q1Value;
    int q2Value;
    int q3Value;
    int q4Value;
    int q5Value;
    int q6Value;
    int q7Value;
    int q8Value;
    int q9Value;
    List <Integer> answerList = new ArrayList <Integer>();
    List <String> questionList = new ArrayList <String>();
    
    List <Test> testList = new ArrayList <Test>();
    List<String> clipsRules = new ArrayList <String>();
    
    public TestEatingDis1(String userName, boolean generalTest) {
        initComponents();
        this.userName = userName;
        this.generalTest = generalTest;
        this.setSize(new Dimension(600,750));        
        //setIcon();
        if(generalTest){
            nextButton.setText("Next");
        }else{
        nextButton.setText("Submit");
        }
        startGroupButtons();
    }
    
    public TestEatingDis1(String userName, boolean generalTest, List <Test> testList, List<String> clipsRules) {
        initComponents();
        this.userName = userName;
        this.generalTest = generalTest;
        this.testList = testList;
        this.clipsRules = clipsRules;
        this.setSize(new Dimension(600,750));        
        //setIcon();
        
        if(generalTest){
            nextButton.setText("Next");
        }else{
        nextButton.setText("Submit");
        }
        
        startGroupButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nextButton = new javax.swing.JToggleButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        q6_2 = new javax.swing.JRadioButton();
        q6_3 = new javax.swing.JRadioButton();
        q3_1 = new javax.swing.JRadioButton();
        q9_0 = new javax.swing.JRadioButton();
        q1_2 = new javax.swing.JRadioButton();
        q9_1 = new javax.swing.JRadioButton();
        q2_1 = new javax.swing.JRadioButton();
        q9_3 = new javax.swing.JRadioButton();
        q2_2 = new javax.swing.JRadioButton();
        q9_2 = new javax.swing.JRadioButton();
        q3_2 = new javax.swing.JRadioButton();
        q4_1 = new javax.swing.JRadioButton();
        q2_0 = new javax.swing.JRadioButton();
        q3_0 = new javax.swing.JRadioButton();
        q5_1 = new javax.swing.JRadioButton();
        q5_0 = new javax.swing.JRadioButton();
        q6_1 = new javax.swing.JRadioButton();
        q4_2 = new javax.swing.JRadioButton();
        q5_3 = new javax.swing.JRadioButton();
        q4_0 = new javax.swing.JRadioButton();
        q2_3 = new javax.swing.JRadioButton();
        q1_3 = new javax.swing.JRadioButton();
        q3_3 = new javax.swing.JRadioButton();
        q6_0 = new javax.swing.JRadioButton();
        q5_2 = new javax.swing.JRadioButton();
        q4_3 = new javax.swing.JRadioButton();
        q1_1 = new javax.swing.JRadioButton();
        q1_0 = new javax.swing.JRadioButton();
        q7_2 = new javax.swing.JRadioButton();
        q7_3 = new javax.swing.JRadioButton();
        q7_1 = new javax.swing.JRadioButton();
        q7_0 = new javax.swing.JRadioButton();
        q8_2 = new javax.swing.JRadioButton();
        q8_3 = new javax.swing.JRadioButton();
        q8_1 = new javax.swing.JRadioButton();
        q8_0 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("I feel that others would prefer if I ate more");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("I am terrified about being overweight");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("I avoid eating when I am hungry");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("I vomit after I have eaten");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("that I eat");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("that I may not be able to stop");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("I find myself preoccupied with food");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("I have gone on eating binges where I feel ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("I cut my food into small pieces");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("I aware of the calorie content of foods ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("I particularly avoid food with a high");

        nextButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("carbohydrate content (i.e. bread, rice, etc)");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("0    1    2    3");

        q6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6_2ActionPerformed(evt);
            }
        });

        q6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6_3ActionPerformed(evt);
            }
        });

        q3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3_1ActionPerformed(evt);
            }
        });

        q9_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9_0ActionPerformed(evt);
            }
        });

        q1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1_2ActionPerformed(evt);
            }
        });

        q9_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9_1ActionPerformed(evt);
            }
        });

        q2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2_1ActionPerformed(evt);
            }
        });

        q9_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9_3ActionPerformed(evt);
            }
        });

        q2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2_2ActionPerformed(evt);
            }
        });

        q9_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9_2ActionPerformed(evt);
            }
        });

        q3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3_2ActionPerformed(evt);
            }
        });

        q4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4_1ActionPerformed(evt);
            }
        });

        q2_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2_0ActionPerformed(evt);
            }
        });

        q3_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3_0ActionPerformed(evt);
            }
        });

        q5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5_1ActionPerformed(evt);
            }
        });

        q5_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5_0ActionPerformed(evt);
            }
        });

        q6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6_1ActionPerformed(evt);
            }
        });

        q4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4_2ActionPerformed(evt);
            }
        });

        q5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5_3ActionPerformed(evt);
            }
        });

        q4_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4_0ActionPerformed(evt);
            }
        });

        q2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2_3ActionPerformed(evt);
            }
        });

        q1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1_3ActionPerformed(evt);
            }
        });

        q3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3_3ActionPerformed(evt);
            }
        });

        q6_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6_0ActionPerformed(evt);
            }
        });

        q5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5_2ActionPerformed(evt);
            }
        });

        q4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4_3ActionPerformed(evt);
            }
        });

        q1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1_1ActionPerformed(evt);
            }
        });

        q1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1_0ActionPerformed(evt);
            }
        });

        q7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7_2ActionPerformed(evt);
            }
        });

        q7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7_3ActionPerformed(evt);
            }
        });

        q7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7_1ActionPerformed(evt);
            }
        });

        q7_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7_0ActionPerformed(evt);
            }
        });

        q8_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8_2ActionPerformed(evt);
            }
        });

        q8_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8_3ActionPerformed(evt);
            }
        });

        q8_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8_1ActionPerformed(evt);
            }
        });

        q8_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8_0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nextButton)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel13))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(q2_0)
                                                        .addComponent(q1_0))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(q1_1)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(q1_2)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(q1_3))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(q2_1)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(q2_2)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(q2_3))))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(q6_0)
                                                        .addComponent(q5_0))
                                                    .addGap(18, 18, 18)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(q5_1)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(q5_2)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(q5_3))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(q6_1)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(q6_2)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(q6_3))))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(q9_0)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(q9_1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(q9_2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(q9_3))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(q8_0)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(q8_1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(q8_2)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(q8_3)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(q3_0)
                                                .addGap(18, 18, 18)
                                                .addComponent(q3_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(q3_2)
                                                .addGap(21, 21, 21)
                                                .addComponent(q3_3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(q4_0)
                                                .addGap(18, 18, 18)
                                                .addComponent(q4_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(q4_2)
                                                .addGap(18, 18, 18)
                                                .addComponent(q4_3))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(q7_0)
                                                .addGap(18, 18, 18)
                                                .addComponent(q7_1)
                                                .addGap(18, 18, 18)
                                                .addComponent(q7_2)
                                                .addGap(18, 18, 18)
                                                .addComponent(q7_3)))
                                        .addGap(5, 5, 5)))))
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1_3)
                            .addComponent(q1_2)
                            .addComponent(q1_1)
                            .addComponent(q1_0))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(q2_3)
                                    .addComponent(q2_2))
                                .addComponent(q2_0, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(q2_1))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(q3_2)
                    .addComponent(q3_3)
                    .addComponent(q3_1)
                    .addComponent(q3_0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q4_3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q4_2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q4_1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q4_0, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(59, 59, 59)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(q5_2)
                        .addComponent(q5_3))
                    .addComponent(q5_0)
                    .addComponent(q5_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q6_3)
                            .addComponent(q6_0)
                            .addComponent(q6_2)
                            .addComponent(q6_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q7_3)
                            .addComponent(q7_0)
                            .addComponent(q7_2)
                            .addComponent(q7_1))))
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(q8_3)
                    .addComponent(q8_0)
                    .addComponent(q8_2)
                    .addComponent(q8_1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(q9_1)
                    .addComponent(q9_0)
                    .addComponent(q9_2)
                    .addComponent(q9_3))
                .addGap(18, 18, 18)
                .addComponent(nextButton)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        boolean q1Check = q1_0.isSelected() || q1_1.isSelected() || q1_2.isSelected() || q1_3.isSelected();
        boolean q2Check = q2_0.isSelected() || q2_1.isSelected() || q2_2.isSelected() || q2_3.isSelected();
        boolean q3Check = q3_0.isSelected() || q3_1.isSelected() || q3_2.isSelected() || q3_3.isSelected();
        boolean q4Check = q4_0.isSelected() || q4_1.isSelected() || q4_2.isSelected() || q4_3.isSelected();
        boolean q5Check = q5_0.isSelected() || q5_1.isSelected() || q5_2.isSelected() || q5_3.isSelected();
        boolean q6Check = q6_0.isSelected() || q6_1.isSelected() || q6_2.isSelected() || q6_3.isSelected();
        boolean q7Check = q7_0.isSelected() || q7_1.isSelected() || q7_2.isSelected() || q7_3.isSelected();
        boolean q8Check = q8_0.isSelected() || q8_1.isSelected() || q8_2.isSelected() || q8_3.isSelected();
        boolean q9Check = q9_0.isSelected() || q9_1.isSelected() || q9_2.isSelected() || q9_3.isSelected();
        
        if(q1Check && q2Check && q3Check && q4Check && q5Check && q6Check && q7Check && q8Check && q9Check){
        
        setValueParameters();
        
        answerList.add(q1Value);
        answerList.add(q2Value);
        answerList.add(q3Value);
        answerList.add(q4Value);
        answerList.add(q5Value);
        answerList.add(q6Value);
        answerList.add(q7Value);
        answerList.add(q8Value);
        answerList.add(q9Value);
        
        System.out.println(answerList);
        System.out.println("Answers from first page saved");
        
        TestEatingDis2 eatingFrame = new TestEatingDis2(userName, answerList, generalTest, testList, clipsRules);
        eatingFrame.setLocationRelativeTo(null);
        eatingFrame.setVisible(true);
        this.dispose();
        
        }
        else{
        JOptionPane.showMessageDialog(new JFrame(), "Please answer all the answers!", "Error",JOptionPane.ERROR_MESSAGE);    
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void q6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6_2ActionPerformed

    private void q6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6_3ActionPerformed

    private void q3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3_1ActionPerformed

    private void q9_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9_0ActionPerformed

    private void q1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1_2ActionPerformed

    private void q9_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9_1ActionPerformed

    private void q2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2_1ActionPerformed

    private void q9_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9_3ActionPerformed

    private void q2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2_2ActionPerformed

    private void q9_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9_2ActionPerformed

    private void q3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3_2ActionPerformed

    private void q4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4_1ActionPerformed

    private void q2_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2_0ActionPerformed

    private void q3_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3_0ActionPerformed

    private void q5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5_1ActionPerformed

    private void q5_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5_0ActionPerformed

    private void q6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6_1ActionPerformed

    private void q4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4_2ActionPerformed

    private void q5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5_3ActionPerformed

    private void q4_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4_0ActionPerformed

    private void q2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2_3ActionPerformed

    private void q1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1_3ActionPerformed

    private void q3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3_3ActionPerformed

    private void q6_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6_0ActionPerformed

    private void q5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5_2ActionPerformed

    private void q4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4_3ActionPerformed

    private void q1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1_1ActionPerformed

    private void q1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1_0ActionPerformed

    private void q7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7_2ActionPerformed

    private void q7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7_3ActionPerformed

    private void q7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7_1ActionPerformed

    private void q7_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7_0ActionPerformed

    private void q8_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8_2ActionPerformed

    private void q8_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8_3ActionPerformed

    private void q8_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8_1ActionPerformed

    private void q8_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8_0ActionPerformed

    public void startGroupButtons(){
  
        ButtonGroup groupQ1 = new ButtonGroup();
        groupQ1.add(q1_0);
        groupQ1.add(q1_1);
        groupQ1.add(q1_2);
        groupQ1.add(q1_3);
        
        ButtonGroup groupQ2 = new ButtonGroup();
        groupQ2.add(q2_0);
        groupQ2.add(q2_1);
        groupQ2.add(q2_2);
        groupQ2.add(q2_3);
        
        ButtonGroup groupQ3 = new ButtonGroup();
        groupQ3.add(q3_0);
        groupQ3.add(q3_1);
        groupQ3.add(q3_2);
        groupQ3.add(q3_3);
        
        ButtonGroup groupQ4 = new ButtonGroup();
        groupQ4.add(q4_0);
        groupQ4.add(q4_1);
        groupQ4.add(q4_2);
        groupQ4.add(q4_3);
        
        ButtonGroup groupQ5 = new ButtonGroup();
        groupQ5.add(q5_0);
        groupQ5.add(q5_1);
        groupQ5.add(q5_2);
        groupQ5.add(q5_3);
        
        ButtonGroup groupQ6 = new ButtonGroup();
        groupQ6.add(q6_0);
        groupQ6.add(q6_1);
        groupQ6.add(q6_2);
        groupQ6.add(q6_3);
        
        ButtonGroup groupQ7 = new ButtonGroup();
        groupQ7.add(q7_0);
        groupQ7.add(q7_1);
        groupQ7.add(q7_2);
        groupQ7.add(q7_3);
                
        ButtonGroup groupQ8 = new ButtonGroup();
        groupQ8.add(q8_0);
        groupQ8.add(q8_1);
        groupQ8.add(q8_2);
        groupQ8.add(q8_3);
                
        ButtonGroup groupQ9 = new ButtonGroup();
        groupQ9.add(q9_0);
        groupQ9.add(q9_1);
        groupQ9.add(q9_2);
        groupQ9.add(q9_3);
    }
    
    public void setValueParameters(){
        
        //Question 1
        if (q1_0.isSelected()){
            q1Value = 0;
        }
        else if (q1_1.isSelected()){
            q1Value = 1;
        }
        else if (q1_2.isSelected()){
            q1Value = 2;
        }
        else if (q1_3.isSelected()){
            q1Value = 3;
        }
        
        //Question 2
        if (q2_0.isSelected()){
            q2Value = 0;
        }
        else if (q2_1.isSelected()){
            q2Value = 1;
        }
        else if (q2_2.isSelected()){
            q2Value = 2;
        }
        else if (q2_3.isSelected()){
            q2Value = 3;
        }
        
        //Question 3
        if (q3_0.isSelected()){
            q3Value = 0;
        }
        else if (q3_1.isSelected()){
            q3Value = 1;
        }
        else if (q3_2.isSelected()){
            q3Value = 2;
        }
        else if (q3_3.isSelected()){
            q3Value = 3;
        }
        
        //Question 4
        if (q4_0.isSelected()){
            q4Value = 0;
        }
        else if (q4_1.isSelected()){
            q4Value = 1;
        }
        else if (q4_2.isSelected()){
            q4Value = 2;
        }
        else if (q4_3.isSelected()){
            q4Value = 3;
        }
        
        //Question 5
        if (q5_0.isSelected()){
            q5Value = 0;
        }
        else if (q5_1.isSelected()){
            q5Value = 1;
        }
        else if (q5_2.isSelected()){
            q5Value = 2;
        }
        else if (q5_3.isSelected()){
            q5Value = 3;
        }
        
        //Question 6
        if (q6_0.isSelected()){
            q6Value = 0;
        }
        else if (q6_1.isSelected()){
            q6Value = 1;
        }
        else if (q6_2.isSelected()){
            q6Value = 2;
        }
        else if (q6_3.isSelected()){
            q6Value = 3;
        }
        
        //Question 7
        if (q7_0.isSelected()){
            q7Value = 0;
        }
        else if (q7_1.isSelected()){
            q7Value = 1;
        }
        else if (q7_2.isSelected()){
            q7Value = 2;
        }
        else if (q7_3.isSelected()){
            q7Value = 3;
        }
        
        //Question 7
        if (q8_0.isSelected()){
            q8Value = 0;
        }
        else if (q8_1.isSelected()){
            q8Value = 1;
        }
        else if (q8_2.isSelected()){
            q8Value = 2;
        }
        else if (q8_3.isSelected()){
            q8Value = 3;
        }
        
        //Question 7
        if (q9_0.isSelected()){
            q9Value = 0;
        }
        else if (q9_1.isSelected()){
            q9Value = 1;
        }
        else if (q9_2.isSelected()){
            q9Value = 2;
        }
        else if (q9_3.isSelected()){
            q9Value = 3;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton nextButton;
    private javax.swing.JRadioButton q1_0;
    private javax.swing.JRadioButton q1_1;
    private javax.swing.JRadioButton q1_2;
    private javax.swing.JRadioButton q1_3;
    private javax.swing.JRadioButton q2_0;
    private javax.swing.JRadioButton q2_1;
    private javax.swing.JRadioButton q2_2;
    private javax.swing.JRadioButton q2_3;
    private javax.swing.JRadioButton q3_0;
    private javax.swing.JRadioButton q3_1;
    private javax.swing.JRadioButton q3_2;
    private javax.swing.JRadioButton q3_3;
    private javax.swing.JRadioButton q4_0;
    private javax.swing.JRadioButton q4_1;
    private javax.swing.JRadioButton q4_2;
    private javax.swing.JRadioButton q4_3;
    private javax.swing.JRadioButton q5_0;
    private javax.swing.JRadioButton q5_1;
    private javax.swing.JRadioButton q5_2;
    private javax.swing.JRadioButton q5_3;
    private javax.swing.JRadioButton q6_0;
    private javax.swing.JRadioButton q6_1;
    private javax.swing.JRadioButton q6_2;
    private javax.swing.JRadioButton q6_3;
    private javax.swing.JRadioButton q7_0;
    private javax.swing.JRadioButton q7_1;
    private javax.swing.JRadioButton q7_2;
    private javax.swing.JRadioButton q7_3;
    private javax.swing.JRadioButton q8_0;
    private javax.swing.JRadioButton q8_1;
    private javax.swing.JRadioButton q8_2;
    private javax.swing.JRadioButton q8_3;
    private javax.swing.JRadioButton q9_0;
    private javax.swing.JRadioButton q9_1;
    private javax.swing.JRadioButton q9_2;
    private javax.swing.JRadioButton q9_3;
    // End of variables declaration//GEN-END:variables
}
