/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Pojos.Test;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.Dimension;

/**
 *
 * @author annys
 */
public class TestOCD1 extends javax.swing.JFrame {

    String userName;
    boolean generalTest = false;
    int q1Value;
    int q2Value;
    int q3Value;
    int q4Value;
    int q5Value;
    int q6Value;
    int q7Value;
    int q8Value;
    int q9Value;
    List <Integer> answerList = new ArrayList <Integer>();
    List <String> questionList = new ArrayList <String>();
    
    List <Test> testList = new ArrayList <Test>();
    List<String> clipsRules = new ArrayList <String>();
    
    public TestOCD1(String userName, boolean generalTest) {
        initComponents();
        this.userName = userName;
        this.generalTest = generalTest;
        this.setSize(new Dimension(600,750));        
        //setIcon();
        if(generalTest){
            nextButton.setText("Next");
        }else{
        nextButton.setText("Submit");
        }
        startGroupButtons();
    }
    
    public TestOCD1(String userName, boolean generalTest, List <Test> testList, List<String> clipsRules) {
        initComponents();
        this.userName = userName;
        this.generalTest = generalTest;
        this.testList = testList;
        this.clipsRules = clipsRules;
        this.setSize(new Dimension(600,750));        
        //setIcon();
        if(generalTest){
            nextButton.setText("Next");
        }else{
        nextButton.setText("Submit");
        }
        startGroupButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nextButton = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        q6_2 = new javax.swing.JRadioButton();
        q6_3 = new javax.swing.JRadioButton();
        q3_1 = new javax.swing.JRadioButton();
        q9_0 = new javax.swing.JRadioButton();
        q1_2 = new javax.swing.JRadioButton();
        q9_1 = new javax.swing.JRadioButton();
        q2_1 = new javax.swing.JRadioButton();
        q9_3 = new javax.swing.JRadioButton();
        q2_2 = new javax.swing.JRadioButton();
        q9_2 = new javax.swing.JRadioButton();
        q3_2 = new javax.swing.JRadioButton();
        q4_1 = new javax.swing.JRadioButton();
        q2_0 = new javax.swing.JRadioButton();
        q3_0 = new javax.swing.JRadioButton();
        q5_1 = new javax.swing.JRadioButton();
        q5_0 = new javax.swing.JRadioButton();
        q6_1 = new javax.swing.JRadioButton();
        q4_2 = new javax.swing.JRadioButton();
        q5_3 = new javax.swing.JRadioButton();
        q4_0 = new javax.swing.JRadioButton();
        q2_3 = new javax.swing.JRadioButton();
        q1_3 = new javax.swing.JRadioButton();
        q3_3 = new javax.swing.JRadioButton();
        q6_0 = new javax.swing.JRadioButton();
        q5_2 = new javax.swing.JRadioButton();
        q4_3 = new javax.swing.JRadioButton();
        q1_1 = new javax.swing.JRadioButton();
        q1_0 = new javax.swing.JRadioButton();
        q7_2 = new javax.swing.JRadioButton();
        q7_3 = new javax.swing.JRadioButton();
        q7_1 = new javax.swing.JRadioButton();
        q7_0 = new javax.swing.JRadioButton();
        q8_2 = new javax.swing.JRadioButton();
        q8_3 = new javax.swing.JRadioButton();
        q8_1 = new javax.swing.JRadioButton();
        q8_0 = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("I repeatedly check doors, windows, drawers, etc");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("I have saved up so many things that ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("I check things more often than necessary");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("I get upset if others change the way ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("I get upset if objects are not arranged properly");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("I feel compelled to count while I am doing things");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("I find it difficult to touch an object when ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("I find it difficult to control my own thoughts");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("I collect things I do not need");

        nextButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("0    1    2    3");

        q6_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6_2ActionPerformed(evt);
            }
        });

        q6_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6_3ActionPerformed(evt);
            }
        });

        q3_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3_1ActionPerformed(evt);
            }
        });

        q9_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9_0ActionPerformed(evt);
            }
        });

        q1_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1_2ActionPerformed(evt);
            }
        });

        q9_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9_1ActionPerformed(evt);
            }
        });

        q2_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2_1ActionPerformed(evt);
            }
        });

        q9_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9_3ActionPerformed(evt);
            }
        });

        q2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2_2ActionPerformed(evt);
            }
        });

        q9_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9_2ActionPerformed(evt);
            }
        });

        q3_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3_2ActionPerformed(evt);
            }
        });

        q4_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4_1ActionPerformed(evt);
            }
        });

        q2_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2_0ActionPerformed(evt);
            }
        });

        q3_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3_0ActionPerformed(evt);
            }
        });

        q5_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5_1ActionPerformed(evt);
            }
        });

        q5_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5_0ActionPerformed(evt);
            }
        });

        q6_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6_1ActionPerformed(evt);
            }
        });

        q4_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4_2ActionPerformed(evt);
            }
        });

        q5_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5_3ActionPerformed(evt);
            }
        });

        q4_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4_0ActionPerformed(evt);
            }
        });

        q2_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2_3ActionPerformed(evt);
            }
        });

        q1_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1_3ActionPerformed(evt);
            }
        });

        q3_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3_3ActionPerformed(evt);
            }
        });

        q6_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6_0ActionPerformed(evt);
            }
        });

        q5_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5_2ActionPerformed(evt);
            }
        });

        q4_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4_3ActionPerformed(evt);
            }
        });

        q1_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1_1ActionPerformed(evt);
            }
        });

        q1_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1_0ActionPerformed(evt);
            }
        });

        q7_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7_2ActionPerformed(evt);
            }
        });

        q7_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7_3ActionPerformed(evt);
            }
        });

        q7_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7_1ActionPerformed(evt);
            }
        });

        q7_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7_0ActionPerformed(evt);
            }
        });

        q8_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8_2ActionPerformed(evt);
            }
        });

        q8_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8_3ActionPerformed(evt);
            }
        });

        q8_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8_1ActionPerformed(evt);
            }
        });

        q8_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8_0ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("that they get in the way");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("I know it has been touched by strangers or certain people ");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("I have arranged things");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(nextButton))
                    .addComponent(jLabel16)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel14))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(q1_0)
                                .addGap(18, 18, 18)
                                .addComponent(q1_1)
                                .addGap(18, 18, 18)
                                .addComponent(q1_2)
                                .addGap(18, 18, 18)
                                .addComponent(q1_3))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel19)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q8_0)
                                        .addGap(18, 18, 18)
                                        .addComponent(q8_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(q8_2)
                                        .addGap(18, 18, 18)
                                        .addComponent(q8_3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q9_0)
                                        .addGap(18, 18, 18)
                                        .addComponent(q9_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(q9_2)
                                        .addGap(18, 18, 18)
                                        .addComponent(q9_3)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(q7_0)
                                    .addGap(18, 18, 18)
                                    .addComponent(q7_1)
                                    .addGap(18, 18, 18)
                                    .addComponent(q7_2)
                                    .addGap(18, 18, 18)
                                    .addComponent(q7_3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(q6_0)
                                    .addGap(18, 18, 18)
                                    .addComponent(q6_1)
                                    .addGap(18, 18, 18)
                                    .addComponent(q6_2)
                                    .addGap(18, 18, 18)
                                    .addComponent(q6_3))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q2_0)
                                        .addGap(18, 18, 18)
                                        .addComponent(q2_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(q2_2)
                                        .addGap(18, 18, 18)
                                        .addComponent(q2_3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q3_0)
                                        .addGap(18, 18, 18)
                                        .addComponent(q3_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(q3_2)
                                        .addGap(21, 21, 21)
                                        .addComponent(q3_3))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q5_0)
                                        .addGap(18, 18, 18)
                                        .addComponent(q5_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(q5_2)
                                        .addGap(18, 18, 18)
                                        .addComponent(q5_3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(q4_0)
                                        .addGap(18, 18, 18)
                                        .addComponent(q4_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(q4_2)
                                        .addGap(18, 18, 18)
                                        .addComponent(q4_3)))))))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(476, 476, 476))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14))
                    .addComponent(q1_3)
                    .addComponent(q1_2)
                    .addComponent(q1_1)
                    .addComponent(q1_0))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(q2_3)
                                    .addComponent(q2_2))
                                .addComponent(q2_0, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(q2_1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q3_2)
                            .addComponent(q3_3)
                            .addComponent(q3_1)
                            .addComponent(q3_0))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(q4_3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(q4_2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(q4_1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(q4_0, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(q5_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q5_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q5_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(q5_1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel16)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(55, 55, 55))
                            .addComponent(jLabel7))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel10)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q6_3)
                            .addComponent(q6_0)
                            .addComponent(q6_2)
                            .addComponent(q6_1))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q7_3)
                            .addComponent(q7_0)
                            .addComponent(q7_2)
                            .addComponent(q7_1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q8_3)
                            .addComponent(q8_0)
                            .addComponent(q8_2)
                            .addComponent(q8_1))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q9_1)
                            .addComponent(q9_0)
                            .addComponent(q9_2)
                            .addComponent(q9_3))))
                .addGap(20, 20, 20)
                .addComponent(nextButton)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q8_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8_0ActionPerformed

    private void q8_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8_1ActionPerformed

    private void q8_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8_3ActionPerformed

    private void q8_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q8_2ActionPerformed

    private void q7_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7_0ActionPerformed

    private void q7_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7_1ActionPerformed

    private void q7_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7_3ActionPerformed

    private void q7_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q7_2ActionPerformed

    private void q1_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1_0ActionPerformed

    private void q1_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1_1ActionPerformed

    private void q4_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4_3ActionPerformed

    private void q5_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5_2ActionPerformed

    private void q6_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6_0ActionPerformed

    private void q3_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3_3ActionPerformed

    private void q1_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1_3ActionPerformed

    private void q2_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2_3ActionPerformed

    private void q4_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4_0ActionPerformed

    private void q5_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5_3ActionPerformed

    private void q4_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4_2ActionPerformed

    private void q6_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6_1ActionPerformed

    private void q5_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5_0ActionPerformed

    private void q5_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q5_1ActionPerformed

    private void q3_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3_0ActionPerformed

    private void q2_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2_0ActionPerformed

    private void q4_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q4_1ActionPerformed

    private void q3_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3_2ActionPerformed

    private void q9_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9_2ActionPerformed

    private void q2_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2_2ActionPerformed

    private void q9_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9_3ActionPerformed

    private void q2_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2_1ActionPerformed

    private void q9_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9_1ActionPerformed

    private void q1_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1_2ActionPerformed

    private void q9_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q9_0ActionPerformed

    private void q3_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q3_1ActionPerformed

    private void q6_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6_3ActionPerformed

    private void q6_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q6_2ActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
       boolean q1Check = q1_0.isSelected() || q1_1.isSelected() || q1_2.isSelected() || q1_3.isSelected();
        boolean q2Check = q2_0.isSelected() || q2_1.isSelected() || q2_2.isSelected() || q2_3.isSelected();
        boolean q3Check = q3_0.isSelected() || q3_1.isSelected() || q3_2.isSelected() || q3_3.isSelected();
        boolean q4Check = q4_0.isSelected() || q4_1.isSelected() || q4_2.isSelected() || q4_3.isSelected();
        boolean q5Check = q5_0.isSelected() || q5_1.isSelected() || q5_2.isSelected() || q5_3.isSelected();
        boolean q6Check = q6_0.isSelected() || q6_1.isSelected() || q6_2.isSelected() || q6_3.isSelected();
        boolean q7Check = q7_0.isSelected() || q7_1.isSelected() || q7_2.isSelected() || q7_3.isSelected();
        boolean q8Check = q8_0.isSelected() || q8_1.isSelected() || q8_2.isSelected() || q8_3.isSelected();
        boolean q9Check = q9_0.isSelected() || q9_1.isSelected() || q9_2.isSelected() || q9_3.isSelected();
        
        if(q1Check && q2Check && q3Check && q4Check && q5Check && q6Check && q7Check && q8Check && q9Check){
        
        setValueParameters();
        
        answerList.add(q1Value);
        answerList.add(q2Value);
        answerList.add(q3Value);
        answerList.add(q4Value);
        answerList.add(q5Value);
        answerList.add(q6Value);
        answerList.add(q7Value);
        answerList.add(q8Value);
        answerList.add(q9Value);
        
        System.out.println(answerList);
        System.out.println("Answers from first page saved");
        TestOCD2 obsessiveFrame;
        if(generalTest){
            obsessiveFrame = new TestOCD2(userName, answerList, generalTest, testList, clipsRules);
        } else {
            obsessiveFrame = new TestOCD2(userName, answerList, generalTest);
        }
        obsessiveFrame.setLocationRelativeTo(null);
        obsessiveFrame.setVisible(true);
        this.dispose();
        
        }
        else{
        JOptionPane.showMessageDialog(new JFrame(), "Please answer all the answers!", "Error",JOptionPane.ERROR_MESSAGE);    
        }
    }//GEN-LAST:event_nextButtonActionPerformed

     public void startGroupButtons(){
  
        ButtonGroup groupQ1 = new ButtonGroup();
        groupQ1.add(q1_0);
        groupQ1.add(q1_1);
        groupQ1.add(q1_2);
        groupQ1.add(q1_3);
        
        ButtonGroup groupQ2 = new ButtonGroup();
        groupQ2.add(q2_0);
        groupQ2.add(q2_1);
        groupQ2.add(q2_2);
        groupQ2.add(q2_3);
        
        ButtonGroup groupQ3 = new ButtonGroup();
        groupQ3.add(q3_0);
        groupQ3.add(q3_1);
        groupQ3.add(q3_2);
        groupQ3.add(q3_3);
        
        ButtonGroup groupQ4 = new ButtonGroup();
        groupQ4.add(q4_0);
        groupQ4.add(q4_1);
        groupQ4.add(q4_2);
        groupQ4.add(q4_3);
        
        ButtonGroup groupQ5 = new ButtonGroup();
        groupQ5.add(q5_0);
        groupQ5.add(q5_1);
        groupQ5.add(q5_2);
        groupQ5.add(q5_3);
        
        ButtonGroup groupQ6 = new ButtonGroup();
        groupQ6.add(q6_0);
        groupQ6.add(q6_1);
        groupQ6.add(q6_2);
        groupQ6.add(q6_3);
        
        ButtonGroup groupQ7 = new ButtonGroup();
        groupQ7.add(q7_0);
        groupQ7.add(q7_1);
        groupQ7.add(q7_2);
        groupQ7.add(q7_3);
                
        ButtonGroup groupQ8 = new ButtonGroup();
        groupQ8.add(q8_0);
        groupQ8.add(q8_1);
        groupQ8.add(q8_2);
        groupQ8.add(q8_3);
                
        ButtonGroup groupQ9 = new ButtonGroup();
        groupQ9.add(q9_0);
        groupQ9.add(q9_1);
        groupQ9.add(q9_2);
        groupQ9.add(q9_3);
    }
    
    public void setValueParameters(){
        
        //Question 1
        if (q1_0.isSelected()){
            q1Value = 0;
        }
        else if (q1_1.isSelected()){
            q1Value = 1;
        }
        else if (q1_2.isSelected()){
            q1Value = 2;
        }
        else if (q1_3.isSelected()){
            q1Value = 3;
        }
        
        //Question 2
        if (q2_0.isSelected()){
            q2Value = 0;
        }
        else if (q2_1.isSelected()){
            q2Value = 1;
        }
        else if (q2_2.isSelected()){
            q2Value = 2;
        }
        else if (q2_3.isSelected()){
            q2Value = 3;
        }
        
        //Question 3
        if (q3_0.isSelected()){
            q3Value = 0;
        }
        else if (q3_1.isSelected()){
            q3Value = 1;
        }
        else if (q3_2.isSelected()){
            q3Value = 2;
        }
        else if (q3_3.isSelected()){
            q3Value = 3;
        }
        
        //Question 4
        if (q4_0.isSelected()){
            q4Value = 0;
        }
        else if (q4_1.isSelected()){
            q4Value = 1;
        }
        else if (q4_2.isSelected()){
            q4Value = 2;
        }
        else if (q4_3.isSelected()){
            q4Value = 3;
        }
        
        //Question 5
        if (q5_0.isSelected()){
            q5Value = 0;
        }
        else if (q5_1.isSelected()){
            q5Value = 1;
        }
        else if (q5_2.isSelected()){
            q5Value = 2;
        }
        else if (q5_3.isSelected()){
            q5Value = 3;
        }
        
        //Question 6
        if (q6_0.isSelected()){
            q6Value = 0;
        }
        else if (q6_1.isSelected()){
            q6Value = 1;
        }
        else if (q6_2.isSelected()){
            q6Value = 2;
        }
        else if (q6_3.isSelected()){
            q6Value = 3;
        }
        
        //Question 7
        if (q7_0.isSelected()){
            q7Value = 0;
        }
        else if (q7_1.isSelected()){
            q7Value = 1;
        }
        else if (q7_2.isSelected()){
            q7Value = 2;
        }
        else if (q7_3.isSelected()){
            q7Value = 3;
        }
        
        //Question 7
        if (q8_0.isSelected()){
            q8Value = 0;
        }
        else if (q8_1.isSelected()){
            q8Value = 1;
        }
        else if (q8_2.isSelected()){
            q8Value = 2;
        }
        else if (q8_3.isSelected()){
            q8Value = 3;
        }
        
        //Question 7
        if (q9_0.isSelected()){
            q9Value = 0;
        }
        else if (q9_1.isSelected()){
            q9Value = 1;
        }
        else if (q9_2.isSelected()){
            q9Value = 2;
        }
        else if (q9_3.isSelected()){
            q9Value = 3;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton nextButton;
    private javax.swing.JRadioButton q1_0;
    private javax.swing.JRadioButton q1_1;
    private javax.swing.JRadioButton q1_2;
    private javax.swing.JRadioButton q1_3;
    private javax.swing.JRadioButton q2_0;
    private javax.swing.JRadioButton q2_1;
    private javax.swing.JRadioButton q2_2;
    private javax.swing.JRadioButton q2_3;
    private javax.swing.JRadioButton q3_0;
    private javax.swing.JRadioButton q3_1;
    private javax.swing.JRadioButton q3_2;
    private javax.swing.JRadioButton q3_3;
    private javax.swing.JRadioButton q4_0;
    private javax.swing.JRadioButton q4_1;
    private javax.swing.JRadioButton q4_2;
    private javax.swing.JRadioButton q4_3;
    private javax.swing.JRadioButton q5_0;
    private javax.swing.JRadioButton q5_1;
    private javax.swing.JRadioButton q5_2;
    private javax.swing.JRadioButton q5_3;
    private javax.swing.JRadioButton q6_0;
    private javax.swing.JRadioButton q6_1;
    private javax.swing.JRadioButton q6_2;
    private javax.swing.JRadioButton q6_3;
    private javax.swing.JRadioButton q7_0;
    private javax.swing.JRadioButton q7_1;
    private javax.swing.JRadioButton q7_2;
    private javax.swing.JRadioButton q7_3;
    private javax.swing.JRadioButton q8_0;
    private javax.swing.JRadioButton q8_1;
    private javax.swing.JRadioButton q8_2;
    private javax.swing.JRadioButton q8_3;
    private javax.swing.JRadioButton q9_0;
    private javax.swing.JRadioButton q9_1;
    private javax.swing.JRadioButton q9_2;
    private javax.swing.JRadioButton q9_3;
    // End of variables declaration//GEN-END:variables
}
